name: Zip Resource Pack

on:
  push:
    branches:
      - main  # Runs the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Zip File
        run: |
          zip -r resourcepack.zip * -x ".git*" ".github*" "resourcepack.zip"

      - name: Upload Zip to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: resourcepack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Zip to GitHub Pages
        run: |
          mkdir -p public
          mv resourcepack.zip public/
          touch public/index.html
        shell: bash

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
